services:
  - type: web
    name: legalbot-frontend
    env: node
    buildCommand: npm install  # Install dependencies
    startCommand: ng serve --host 0.0.0.0 --port 3000  # Start Angular in development mode
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: development  # Set environment variable for development
        
