services:
  - type: web
    name: legalbot-frontend
    env: node
    buildCommand: npm install  # Install dependencies
    startCommand: ng serve --host 0.0.0.0 --port 3000  # Start Angular in development mode
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: development  # Set environment variable for development
        
  - type: web
    name: spring-boot-backend
    env: java
    buildCommand: mvn clean package  # Optional, if you want to package the app
    startCommand: mvn spring-boot:run  # Start the Spring Boot application
    autoDeploy: true
