services:
  - type: web
    name: legalbot-frontend
    env: static
    buildCommand: npm install && npm run build --prod
    publishDirectory: LegalBot/dist/LegalBot  # Adjust this path if necessary
    autoDeploy: true
    branch: main  # This can be removed if not using GitHub

  - type: web
    name: spring-boot-backend
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar Backend/target/your-spring-boot-app.jar  # Update with your actual JAR name
    autoDeploy: true
    branch: main  # This can be removed if not using GitHub
